// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Ingredients = sequelize.define('ingredients', {
    name: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    ingredientType: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'ingredients',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Ingredients.associate = (models) => {
    Ingredients.belongsToMany(models.drinks, {
      through: 'drinkIngredientTags',
      foreignKey: 'ingredient_id',
      otherKey: 'drink_id',
      as: 'drinksThroughDrinkIngredientTags',
    });
    Ingredients.hasMany(models.ingredientTags, {
      foreignKey: {
        name: 'ingredientIdKey',
        field: 'ingredient_id',
      },
      as: 'ingredientTags',
    });
  };

  return Ingredients;
};
