// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Menus = sequelize.define('menus', {
    name: {
      type: DataTypes.STRING,
    },
    active: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    menuType: {
      type: DataTypes.STRING,
    },
    position: {
      type: DataTypes.INTEGER,
    },
  }, {
    tableName: 'menus',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Menus.associate = (models) => {
    Menus.belongsTo(models.restaurantes, {
      foreignKey: {
        name: 'restauranteIdKey',
        field: 'restaurante_id',
      },
      as: 'restaurante',
    });
    Menus.hasMany(models.meals, {
      foreignKey: {
        name: 'menuIdKey',
        field: 'menu_id',
      },
      as: 'meals',
    });
    Menus.hasMany(models.drinks, {
      foreignKey: {
        name: 'menuIdKey',
        field: 'menu_id',
      },
      as: 'drinks',
    });
  };

  return Menus;
};
