// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SetMenus = sequelize.define('setMenus', {
    name: {
      type: DataTypes.STRING,
    },
    price: {
      type: DataTypes.DOUBLE,
    },
    active: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'set_menus',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  SetMenus.associate = (models) => {
    SetMenus.belongsTo(models.restaurantes, {
      foreignKey: {
        name: 'restauranteIdKey',
        field: 'restaurante_id',
      },
      as: 'restaurante',
    });
    SetMenus.hasMany(models.orderProducts, {
      foreignKey: {
        name: 'setMenuIdKey',
        field: 'set_menu_id',
      },
      as: 'setMenuOrderProducts',
    });
  };

  return SetMenus;
};
