// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Tables = sequelize.define('tables', {
    tableNumber: {
      type: DataTypes.INTEGER,
    },
    section: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    code: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'tables',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Tables.associate = (models) => {
    Tables.belongsTo(models.restaurantes, {
      foreignKey: {
        name: 'restauranteIdKey',
        field: 'restaurante_id',
      },
      as: 'restaurante',
    });
    Tables.hasMany(models.orderProducts, {
      foreignKey: {
        name: 'tableIdKey',
        field: 'table_id',
      },
      as: 'orderProducts',
    });
  };

  return Tables;
};
